version: "2"
services:
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=karmabox
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - 'postgresdata:/var/lib/postgresql/data'
    ports:
      - 5432:5432
volumes:
  postgresdata:
