const pallet = {
  dark02: "#0E2B83",
  dark01: "#033BE2",
  neutral: "#537EFF",
  light01: "#CCD8FE",
  light02: "#FDFDFF",
  secondaryDark: "#379683",
  secondaryNeutral: "#5CDB95",
  secondaryLight: "#8EE4AF",
  error: "#ff1e1e",
};
export const theme = {
  pallet,
  colors: {
    bodyBackground: pallet.neutral,
    usernameBoxText: pallet.light02,
    usernameInnerBoxBackground: pallet.dark01,
    usernameBoxBackground: pallet.light02,
    usernameBoxKarmaText: pallet.light02,
    liveFeedBackground: pallet.light02,
    signInRightBackground: pallet.dark02,
    signInFontColor: pallet.light02,
    inputBorder: pallet.dark01,
    signInLink: pallet.light02,
    submitButtonBackground: pallet.neutral,
    loadingSpinner: pallet.light02,
    inputFocusBorder: pallet.light01,
    inputBorderSuccess: pallet.secondaryLight,
    inputBorderError: pallet.error,
    noteColor: pallet.light02,
    usernameIsAvailable: pallet.secondaryNeutral,
    usernameIsNotAvailable: pallet.error,
  },
};
